apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-worker
  template:
    metadata:
      labels:
        app: payments-worker
    spec:
      containers:
      - name: payments-worker
        image: payments-worker:latest
        env:
          # ConfigMap
          - name: RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: payments-worker-config
                key: RABBITMQ_HOST
          - name: QUEUE_NAME
            valueFrom:
              configMapKeyRef:
                name: payments-worker-config
                key: QUEUE_NAME
          - name: EXTERNAL_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: payments-worker-config
                key: EXTERNAL_SERVICE_URL
          # Secret
          - name: RABBITMQ_USER
            valueFrom:
              secretKeyRef:
                name: payments-worker-secret
                key: RABBITMQ_USER
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: payments-worker-secret
                key: RABBITMQ_PASSWORD
          - name: EXTERNAL_API_KEY
            valueFrom:
              secretKeyRef:
                name: payments-worker-secret
                key: EXTERNAL_API_KEY